# Generated by Django 3.2.7 on 2021-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlinfo',
            name='diameter',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
