# Generated by Django 3.2.7 on 2021-09-13 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlinfo', '0002_stlinfo_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlinfo',
            name='stl_file',
            field=models.FileField(upload_to='stls/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])]),
        ),
    ]
